### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by JackBekket** [ma1uta/jmsdk#1]
Hi, ma1uta! 

My name is Segey, and I'm reaching out to you, because of your work on matrix clients

I'm currently working on an implementation of hyper-local (firechat style) chats and I want to make it on matrix platform. 

This far I have successfully ported mdns from libp2p to android and have a working solution, but, since I'm not a very experienced developer on java, I need to someone, who can help me re-build riot client with functional I've made. 

Can you suggest me some dev contacts who can have experience in such work, or kindly provide me some tips of how to do such things?

You can contact me in telegram as @sbekket

**Comment by ma1uta** [comment]
Hello, JackBekket!

It is a nice to see that you interesting the Matrix platform. You can ask help from Riot's developers in the #riot-android:matrix.org room. Also you can find the matrix developers in the #matrix-dev:matrix.org.

**Comment by JackBekket** [comment]
Thank you!
