### ISSUE TITLE
[Docs] Missing example for inbound event handler at client-impl

### ISSUE THREAD

**Issue by miny1997** [ma1uta/jmsdk#14]
Hello

I am trying to figure out on how to get, identify and handle events. I copied your example, but it is missing clarification on how to work with events. Please add some documentation on readme.md or an example class.

`SyncLoop syncLoop = new SyncLoop(mxClient.sync(), (syncResponse, syncParams) -> {`
`            //Get event`
`            //Check event type (User joined room)`
`            //Get user and send invitations`
`        });`

`SyncParams params = SyncParams.builder()`
`                .fullState(false)`
`                .presence(null)`
`                .timeout(1000L)`
`                .build();`
`        syncLoop.setInit(params);`
`        ExecutorService service = Executors.newFixedThreadPool(1);`
`        service.submit(syncLoop);`

**Comment by ma1uta** [comment]
https://github.com/ma1uta/jmsdk/blob/master/examples/src/main/java/io/github/ma1uta/matrix/example/SyncExample.java
