### ISSUE TITLE
jsonb-support: module not found: java.json

### ISSUE THREAD

**Issue by brevilo** [ma1uta/jmsdk#22]
Module hell strikes again. I get this when compiling (latest `master`) with Java 11 and an **empty** maven repo:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project jsonb-support: Compilation failure
[ERROR] jsonb-support/src/main/java/module-info.java:[29,29] module not found: java.json
```

**Comment by ma1uta** [comment]
Discussions here: https://github.com/ma1uta/jmsdk/issues/17. I've created the issue of the Jackson https://github.com/FasterXML/jackson-jaxrs-providers/issues/144

**Comment by brevilo** [comment]
Hm, shouldn't these be two independent (but potentially related) issues, given that jackson and json-b are alternatives to each other?

**Comment by brevilo** [comment]
Fix confirmed 👍
