### ISSUE TITLE
Cached RestClientBuilder generates warnings

### ISSUE THREAD

**Issue by diamondq** [ma1uta/jmsdk#9]
Based on v0.11.3:

I'm constantly getting warnings messages about duplicate registrations in RestEasy.

```
19:07:58.080 [main            ] WARN  o.jboss.resteasy.resteasy_jaxrs.i18n RESTEASY002160: Provider instance org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper is already registered.  2nd registration is being ignored.
19:08:01.050 [main            ] WARN  o.jboss.resteasy.resteasy_jaxrs.i18n RESTEASY002160: Provider instance org.jboss.resteasy.microprofile.client.ExceptionMapping is already registered.  2nd registration is being ignored.
19:08:02.181 [main            ] WARN  o.jboss.resteasy.resteasy_jaxrs.i18n RESTEASY002160: Provider instance org.jboss.resteasy.microprofile.client.DefaultMediaTypeFilter is already registered.  2nd registration is being ignored.
```

These occur every time I ask for a MatrixClient.XXX() (ie. sync(), rooms(), clientConfig(), etc.). As far as I can tell, this is because each of those gets the same RestClientBuilder (since it's cached), but builds a new RestClient for the specific API interface.

Unfortunately, RestEasy seems to then go ahead and register a bunch of objects into the client, and since they've been registered by one of the previous ones, it fails.

I haven't tried fixing it, but maybe removing the caching at:
https://github.com/ma1uta/jmsdk/blob/e4dc95ed9e82b5101f1aace311b7930b180256d4/client-impl/src/main/java/io/github/ma1uta/matrix/client/MatrixClient.java#L124

and just build a new one for each API?

I understand that I can just adjust the logging engine to drop these warnings, but I'm always nervous about ignoring too much and losing a meaningful warning.

**Comment by ma1uta** [comment]
Thanks for the issue. I have fixed it in https://github.com/ma1uta/jmsdk/commit/0bfaeb73021613e335fa99330f290e1fcdac587e#diff-2f4cfdade8d572fef09bf5edb8a267a3L124
